# AUTOMATICALLY GENERATED
# DO NOT EDIT THIS FILE DIRECTLY, USE /templates/Gemfile.erb

source "https://gems.ruby-china.com/"


gem "elasticsearch", "~> 6.0"
gem "fluent-plugin-elasticsearch", "~> 4.0.9"

gem "rdkafka", "~> 0.7.0"
gem "fluent-plugin-kafka", "~> 0.17.0"

gem "aws-sdk-s3", "~> 1.101"
gem "fluent-plugin-s3", "~> 1.6.1"

